name: CI for PyTorch Eval Project

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black ruff

      - name: Lint with ruff
        run: ruff .

      - name: Format check with black
        run: black --check .

      - name: Build Docker image
        run: docker build -t pytorch-eval-app:latest .

      - name: Run Docker smoke test
        run: docker run --rm pytorch-eval-app:latest python --version

      - name:  Save evaluation results (if generated)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/
          if-no-files-found: ignore
