name: CI for PyTorch Eval Project

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black ruff

      - name: Lint with ruff
        run: ruff check  .

      - name: Format check with black
        run: black --check .

      - name: Build Docker image
        run: docker build -t pytorch-eval-app:latest .

      - name: Run Docker smoke test
        run: docker run --rm -v ${{ github.workspace }}/results:/app/results  -v ${{ github.workspace }}/example_models:/app/example_models  pytorch-eval-app:latest python --version

      - name: Validate result folder outputs
        run: |
          if [ ! -d "results" ]; then
            echo "Results directory not found!"
            exit 1
          fi
          PT_FILE_COUNT=$(find example_models/ -type f -name '*.pt' | wc -l )
          echo "  Pt file count $PT_FILE_COUNT" 
          REQUIRED_FILE_COUNT=$((PT_FILE_COUNT*3 +3))
          echo "Required File Count $REQUIRED_FILE_COUNT"
          EXISTING_FILE_COUNT=$(find results -mindepth 2 -maxdepth 2 -type f | wc -l)
          
          # Compare
          if [ "$EXISTING_FILE_COUNT" -lt "$REQUIRED_FILE_COUNT" ]; then
            echo "Missing result files!"
            exit 1
          else
            echo "All required result files exist."
          fi
          

      - name: Save evaluation results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/
          if-no-files-found: error

